"""
Digital signature module (hackathon demonstration).

This uses a locally generated RSA key pair to sign and verify certificate
hashes. This DEMONSTRATES the concept of a digital signature the same way a
real government PKI would (sign with a private key, verify with the public
key) but the key pair here is generated automatically for local development
only.

IMPORTANT: In a real government deployment, signing keys would live in a
managed PKI / Hardware Security Module (HSM), never on a web server's disk.
Do not treat the keys generated by this file as production secrets.
"""
import base64
import os

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa

KEY_DIR = os.path.join(os.getcwd(), "config")
PRIVATE_KEY_PATH = os.path.join(KEY_DIR, "dev_private_key.pem")
PUBLIC_KEY_PATH = os.path.join(KEY_DIR, "dev_public_key.pem")


def _ensure_keys_exist():
    os.makedirs(KEY_DIR, exist_ok=True)
    if os.path.exists(PRIVATE_KEY_PATH) and os.path.exists(PUBLIC_KEY_PATH):
        return

    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    public_key = private_key.public_key()

    with open(PRIVATE_KEY_PATH, "wb") as f:
        f.write(
            private_key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.NoEncryption(),
            )
        )

    with open(PUBLIC_KEY_PATH, "wb") as f:
        f.write(
            public_key.public_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PublicFormat.SubjectPublicKeyInfo,
            )
        )


def _load_private_key():
    _ensure_keys_exist()
    with open(PRIVATE_KEY_PATH, "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None)


def _load_public_key():
    _ensure_keys_exist()
    with open(PUBLIC_KEY_PATH, "rb") as f:
        return serialization.load_pem_public_key(f.read())


def sign_hash(hex_hash: str) -> str:
    """Sign a hex hash string, return a base64-encoded signature."""
    private_key = _load_private_key()
    signature = private_key.sign(
        hex_hash.encode("utf-8"),
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH,
        ),
        hashes.SHA256(),
    )
    return base64.b64encode(signature).decode("utf-8")


def verify_signature(hex_hash: str, signature_b64: str) -> bool:
    """Verify that signature_b64 is a valid signature of hex_hash."""
    if not signature_b64:
        return False
    public_key = _load_public_key()
    try:
        signature = base64.b64decode(signature_b64)
        public_key.verify(
            signature,
            hex_hash.encode("utf-8"),
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH,
            ),
            hashes.SHA256(),
        )
        return True
    except Exception:
        return False
